// Generated by scripts/generate-config.js from .env — do not edit by hand.
// Re-run "node scripts/generate-config.js" after changing .env.
window.SARAL_POOJA_CONFIG = {
  "emailjs": {
    "publicKey": "wq102slC1M235GCJ5",
    "serviceId": "service_ddi3lyg",
    "templateId": "template_bnmx4m9"
  }
};
