#!/usr/bin/env node
// Reads .env in the project root and writes config.js, which is the file
// the browser actually loads (a plain static site has no build step to read
// .env directly, so this small script bridges the two).
//
// Usage:
//   node scripts/generate-config.js

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const outPath = path.join(root, 'config.js');

function parseEnv(text) {
  const out = {};
  text.split('\n').forEach(function (line) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eq = trimmed.indexOf('=');
    if (eq === -1) return;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  });
  return out;
}

if (!fs.existsSync(envPath)) {
  console.error('No .env file found at the project root. Copy .env.example to .env first, then fill in your real EmailJS values.');
  process.exit(1);
}

const env = parseEnv(fs.readFileSync(envPath, 'utf8'));

const config = {
  emailjs: {
    publicKey: env.EMAILJS_PUBLIC_KEY || '',
    serviceId: env.EMAILJS_SERVICE_ID || '',
    templateId: env.EMAILJS_TEMPLATE_ID || ''
  }
};

const banner =
  '// Generated by scripts/generate-config.js from .env — do not edit by hand.\n' +
  '// Re-run "node scripts/generate-config.js" after changing .env.\n';
const body = 'window.SARAL_POOJA_CONFIG = ' + JSON.stringify(config, null, 2) + ';\n';

fs.writeFileSync(outPath, banner + body);
console.log('Wrote ' + outPath);

const stillPlaceholder = Object.values(config.emailjs).some(function (v) {
  return !v || v.indexOf('your_') === 0;
});
if (stillPlaceholder) {
  console.log('Note: .env still has placeholder values — the contact form will show a "not configured" message until you add your real EmailJS credentials and re-run this script.');
}
